services:
    dm_theme.twig.delete_form_extension:
        class: Dm\Bundle\ThemeBundle\Twig\DeleteFormExtension
        arguments: [ @twig ]   
        tags:                  
            - { name: twig.extension } 
    dm_them.extension.icon:
        class: Dm\Bundle\ThemeBundle\Extension\IconExtension
        public: false
        tags:
            - { name: knp_menu.factory_extension }
